server:
  port: 18080

spring:
  application:
    name: spring-ai-jmanus-ollama
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          # ollama 模型
          model: qwen3:8b
          temperature: 0.9
    mcp:
      client:
        enabled: false
  # H2 数据库配置
  datasource:
    url: jdbc:h2:file:./h2-data/openmanus_db;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: $FSD#@!@#!#$!12341234
  # JPA 配置
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # H2 控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  file:
    name: ./logs/info.log
  level:
    root: INFO
    # ai 框架 使用 debug。可以查看模型调用日志提示词等
    org.springframework.ai: DEBUG
